= DCB: Direct Consortial Borrowing
Steve Osguthorpe <steve.osguthorpe@k-int.com>

[.lead]
A https://www.k-int.com/[Knowledge Integration] product for https://projectreshare.org/[Project ReShare]

== Introduction

The direct consortial borrowing project aims to address the need of consortia that have already agreed to lend within the network.

== Running

There are currently no other requirements other than having the application.

=== Linux and Mac

After pulling the repository the application can be started by issuing the command

[source,shell,subs="attributes+"]
----
$ ./gradlew run
----

=== Windows

After pulling the repository the application can be started by issuing the command

[source,shell,subs="attributes+"]
----
> gradle.bat run
----

== Deploying
=== Environment variables

The following environment variables are common to all the methods of deployment.

include::deployment/env-vars.adoc[]

include::deployment/docker.adoc[leveloffset=2]
include::deployment/bare-metal-build.adoc[leveloffset=2]

== API Docs

View the link:openapi/[HTTP API documentation^] (Opens in new window).

There is also an interactive version of the API documentation available from a running instance of the application. Assuming the application is running at `http://localhost:8080` visit http://localhost:8080/openapi/ui/index.html
