= DCB: Direct Consortial Borrowing
Steve Osguthorpe <steve.osguthorpe@k-int.com>

[.lead]
A https://www.k-int.com/[Knowledge Integration] project

== Introduction

The direct consortial borrowing project aims to address the need of consortia that have already agreed to lend within the network.

== Running

There are currently no other requirements other than having the application.

=== Linux and Mac

After pulling the repository the application can be started by issuing the command

[source,shell,subs="attributes+"]
----
$ ./gradlew run
----

=== Windows

After pulling the repository the application can be started by issuing the command

[source,shell,subs="attributes+"]
----
> gradle.bat run
----

== Deploying
=== Environment variables

The following environment variables are common to all the methods of deployment.

include::deployment/env-vars.adoc[]

include::deployment/docker.adoc[leveloffset=2]
include::deployment/bare-metal-build.adoc[leveloffset=2]

== Configuring the shared index synchronization

DCB supports either Opensearch or Elasticsearch when maintaining a shared index.
Start by configuring the necessary shared values below and then add the connection properties for your chosen search provider.

[%autowidth.stretch]
|===
|ENV | Description |Required | Example
|DCB_INDEX_NAME |Name of the index representing the shared index    |no |si-index
|DCB_INDEX_USERNAME |Username to communicate with the index service |no |si-user
|DCB_INDEX_PASSWORD |Password to communicate with the index service |no |si-pass

|*Choose 1 of the below* |||
|ELASTICSEARCH_HTTP_HOSTS |1 or more Elasticsearch hosts (Comma separated) |no (See note) |http://localhost:9200
|OPENSEARCH_HTTP_HOSTS |1 or more OpenSearch hosts (Comma separated) |no (See note) |http://localhost:9200
|===

== Metrics

Metrics are available from running instances of the application at `/metrics`.

=== Prometheus

DCB supports providing metrics in the format understood by Prometheus.
By default Prometheus looks for metrics to be published under `/metrics`, but seeing as that is the home of our internal metrics, the prometheus format is instead published under `/prometheus`

== API Docs

View the link:openapi/[HTTP API documentation^] (Opens in new window).

There is also an interactive version of the API documentation available from a running instance of the application. Assuming the application is running at `http://localhost:8080` visit http://localhost:8080/openapi/ui/index.html
