CREATE TABLE inactive_supplier_request (
    id uuid PRIMARY KEY,
    patron_request_id uuid REFERENCES patron_request(id),
    local_item_id varchar(200),
    local_item_barcode varchar(200),
    local_item_location_code varchar(200),
    local_item_status varchar(32),
    local_item_type varchar(32),
    canonical_item_type varchar(32),
    host_lms_code varchar(200),
    status_code varchar(200),
    local_id varchar(200),
    local_status varchar(32),
    virtual_identity_id uuid REFERENCES patron_identity(id),
    local_bib_id varchar(256),
    local_agency varchar(256),
    resolved_agency_id uuid,
    date_created timestamp,
    date_updated timestamp,
    protocol varchar(10),
    raw_local_status varchar(200),
    raw_local_item_status varchar(200),
    local_item_last_check_timestamp timestamp,
    local_request_last_check_timestamp timestamp,
    local_request_status_repeat integer,
    local_item_status_repeat integer
);
