

ReshareDCB is a micronaut application at time of writing (Jan 2023) compiled as a Java 17 source. At that time, k-int are building using the Temurin 7.0.6 Java distro. The project itself has gradle wrapper installed, so no external gradle installation is necessary.

This guidance is intended for organisations wishing to build the raw service executable (I.E. not have the build emit a container).

There is a policy decision which hosting providers need to make: Use the graalvm executable or build a plain old java fat-jar (Or build the skinny jar and do something else). Both options are cleanly described in the gradle build target - run "gradlew tasks" to see the targets possible.

== Build a graalvm executable

You will need the graalvm JDK to build a native executable - instructions tested Jan 2023 with Graalvm 22.3.r17-grl

    ./gradlew nativeCompile

Will create a native executable including ONLY the parts of the JDK needed to run the code. This will output artefacts to dcb/build/native/nativeCompile in the form

    dcb

Which is a native executable that can be run from the command line


== Build a fatjar

    ./gradlew jar

Is the command to execute to build jar options. After execution the dcb/build/libs/

    - dcb-all.jar
    - dcb-jar
    - dcb-runner.jar  

Where the -all.jar jar is the fatjar. .jar is the standard library, and -runner is executable
