package org.olf.dcb.export.model;

import java.util.ArrayList;
import java.util.List;

import org.olf.dcb.core.model.DataAgency;
import org.olf.dcb.core.model.DataHostLms;
import org.olf.dcb.core.model.Library;
import org.olf.dcb.core.model.LibraryContact;
import org.olf.dcb.core.model.LibraryGroup;
import org.olf.dcb.core.model.LibraryGroupMember;
import org.olf.dcb.core.model.Location;
import org.olf.dcb.core.model.NumericRangeMapping;
import org.olf.dcb.core.model.Person;
import org.olf.dcb.core.model.ReferenceValueMapping;
import org.olf.dcb.rules.ObjectRuleset;

import io.micronaut.serde.annotation.Serdeable;
import lombok.Data;
import lombok.ToString;
import lombok.experimental.Accessors;
import services.k_int.tests.ExcludeFromGeneratedCoverageReport;

/**
 * This class is used with the import and export to hold the information associated with configuring 1 or more sites
 */
@Accessors(chain = true)
@Data
@ExcludeFromGeneratedCoverageReport
@Serdeable
@ToString
public class SiteConfiguration {
	public List<DataAgency> agencies;
	public List<DataHostLms> lmsHosts;
	public List<LibraryContact> libraryContacts;
	public List<LibraryGroupMember> libraryGroupMembers;
	public List<LibraryGroup> libraryGroups;
	public List<Library> libraries;
	public List<Location> locations;
	public List<NumericRangeMapping> numericRangeMappings;
	public List<ObjectRuleset> objectRulesets;
	public List<Person> persons;
	public List<ReferenceValueMapping> referenceValueMappings;

	// Contains any errors generated by the export
	public List<String> errors;
	
	public static SiteConfiguration create() {
		SiteConfiguration siteConfiguration = new SiteConfiguration();
		siteConfiguration.agencies = new ArrayList<DataAgency>();
		siteConfiguration.lmsHosts = new ArrayList<DataHostLms>();
		siteConfiguration.libraryContacts = new ArrayList<LibraryContact>();
		siteConfiguration.libraryGroupMembers = new ArrayList<LibraryGroupMember>();
		siteConfiguration.libraryGroups = new ArrayList<LibraryGroup>();
		siteConfiguration.libraries = new ArrayList<Library>();
		siteConfiguration.locations = new ArrayList<Location>();
		siteConfiguration.numericRangeMappings = new ArrayList<NumericRangeMapping>();
		siteConfiguration.objectRulesets = new ArrayList<ObjectRuleset>();
		siteConfiguration.persons = new ArrayList<Person>();
		siteConfiguration.referenceValueMappings = new ArrayList<ReferenceValueMapping>();
		siteConfiguration.errors = new ArrayList<String>();
		return(siteConfiguration);
	}
}
