micronaut:
  application:
    name: dcb
  router:
    static-resources:
      swagger:
        enabled: true
        paths: classpath:META-INF/swagger
        mapping: /openapi/**
      swagger-ui:
        enabled: true
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /openapi/ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /openapi/redoc/**
  security:
    authentication: bearer
    token:
      jwt:
        generator:
          access-token:
            expiration: 600
        signatures:
          secret:
            generator:
              secret: "${token.secret:placeholder}"
              base64: true
              jws-algorithm: HS256
    intercept-url-map:
      - pattern: "/openapi/**"
        access:
          - isAnonymous()
  http:
    client:
      read-timeout: PT30S
      
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

endpoints:
  prometheus:
    sensitive: false

flyway:
  enabled: true
  datasources:
    default:
      enabled: true
      # locations:
      #   - classpath:db/migrations
      # default-schema: r2dbc-poc
      # url: ${DB_URL:`r2dbc:postgresql://localhost:5432/postgres`}
      # username: ${DB_USER:`postgres`}
      # password: ${DB_PASSWORD:`pass`}

db:
  host: localhost
  port: 5432

datasources:
  default:
    enabled: true
    driverClassName: org.postgresql.Driver
    schema-generate: NONE
    db-type: postgresql
    dialect: postgres
    minimumIdol: 0
    maximumPoolSize: 2
    #username: "${db.username:}"
    #password: "${db.password:}"

r2dbc:
  datasources:
    default:
      enabled: true
      # https://micronaut-projects.github.io/micronaut-test-resources/latest/guide/
      # Specify db-type so test resources knows what to provision
      db-type: postgresql
      # url: ${DB_URL:`r2dbc:postgresql://localhost:5432/postgres`}
      # username: ${DB_USER:`postgres`}
      # password: ${DB_PASSWORD:`pass`}
      options:
        driver: pool
        protocol: postgres
        poolName: r2dbc
        maxSize: 20
        initialSize: 5
        maxLifeTime: PT280S
        maxIdleTime: PT240S
        maxAcquireTime: PT6S
      
      # driver: postgresql
      #url: "r2dbc:postgresql://${db.host}:${db.port}/${db.database:}"
      #host: "${db.host:localhost}"
      #username: "${db.username:}"
      #password: "${db.password:}"
      dialect: postgres
      
      schema-generate: NONE

# elasticsearch.httpHosts: http://localhost:9200,http://127.0.0.2:9200
netty:
  default:
    allocator:
      max-order: 3

jackson:
  date-format: "yyyy-MM-dd'T'HH:mm:ssZ"


