package org.olf.reshare.dcb.request.fulfilment;

public interface PatronRequestStatusConstants {
	String SUBMITTED_TO_DCB = "SUBMITTED_TO_DCB";
	String PATRON_VERIFIED = "PATRON_VERIFIED";
	String RESOLVED = "RESOLVED";
	String NO_ITEMS_AVAILABLE_AT_ANY_AGENCY = "NO_ITEMS_AVAILABLE_AT_ANY_AGENCY";
	String REQUEST_PLACED_AT_SUPPLYING_AGENCY = "REQUEST_PLACED_AT_SUPPLYING_AGENCY";
}
