# Simple workflow for deploying static content to GitHub Pages
name: Generate and deploy pages

on:
  push:
    tags:
        - 'v.*'
    branches:
      - 'main'
    paths:
      - 'src/docs/asciidoc/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one "pages" concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    env:
      MICRONAUT_OPENAPI_VIEWS_SPEC: "mapping.path=/reshare-dcb-service/openapi"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: :asciidoctor :staticCopyOpenApi

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Docs path for asciidocs
          path: 'build/docs/asciidoc'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

