name: Test PR (Excludes docs only PRs)

on:
  pull_request:
    paths-ignore:
      - 'src/docs/asciidoc/**' # If all modified paths fall only in this set then this will be ignored
    branches:
      - 'main'
      - 'releases/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: build jacocoTestCoverageVerification

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "build/test-results/test/**/*.xml"

      - uses: actions/upload-artifact@v3.1.0
        if: always() # Upload artefacts even when build fails.
        with:
          name: Build Artifacts
          path: |
            **/build/reports
